const userWithoutPassword = {
  email: 1,
  first_name: 1,
  last_name: 1,
  username: 1,
  age: 1,
  phone: 1,
  location: 1,
  gender: 1,
  marital_status: 1,
  height_feet: 1,
  height_inches: 1,
  weight: 1,
  blood_group: 1,
  created_at: 1,
  updated_at: 1,
  confirmed: 1,
  user_type: 1,
  forgot_password_hash: 1,
  occupation: 1,
  wallet_address: 1,
  customerId: 1,
  country_code: 1,
  ouraring_key: 1,
};

const userWithPassword = {
  email: 1,
  first_name: 1,
  last_name: 1,
  username: 1,
  age: 1,
  phone: 1,
  location: 1,
  gender: 1,
  marital_status: 1,
  height_feet: 1,
  height_inches: 1,
  weight: 1,
  blood_group: 1,
  created_at: 1,
  updated_at: 1,
  is_deleted: 1,
  password: 1,
  confirmed: 1,
  otp: 1,
  otp_expiry_time: 1,
  forgot_password_hash: 1,
  user_type: 1,
  occupation: 1,
  wallet_address: 1,
  customerId: 1,
  country_code: 1,
  ouraring_key: 1,
};

module.exports = {
  userWithoutPassword,
  userWithPassword,
};
